spring: 
 profiles:  
  active: -dev
        
-----        
        
spring:	
 profiles: 
  application: 
   name: microservicecloud-config-atguigu-dev

-----
      
spring: 
 profiles: test #测试坏境 
  application: 
   name: microservicecloud-config-atguigu-test